### ISSUE TITLE
Individual houseguest pages

### ISSUE THREAD

**Issue by langermank** [Stock-Watch-App/Stockwatch#10]
Data needed:
- Houseguest
- HG image
- Current stats (rating, price)
- Projections
- Historical ratings by LFC
- Historical price

**Comment by tbirrell** [comment]
The initial design will be 3 rows. The first row will be the HG's projection section copied over. The second will be a table with the historical rating data by all 3 LFC and audience (and final rating). The bottom "row" will be an as yet undetermined chart to show prices (and maybe rating) over time.

Backend work for this is collecting the data and passing it forward, then setting up the blade and vue components so that frontend can build the look and layout.
