### ISSUE TITLE
Perfect play

### ISSUE THREAD

**Issue by langermank** [Stock-Watch-App/Stockwatch#12]
Need details

**Comment by tbirrell** [comment]
This is a neat thing to have, but given the nature of the game, its something that will quickly become untethered from the reality of the situation. Last week's perfect winnings fund this week's perfect winnings fund next week's perfect winnings, so even I got this week right, I won't be anywhere close to the perfect player, because I didn't get last week right, and thus started with a different bank. 

All that to say, I think this is a very low priority, and perhaps should be left to the stat people for the time being.
